[tool.poetry]
name = "video-analysis-assistant"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ffmpeg = "^1.4"
opencv-python = "^4.10.0.84"
openai = "^1.42.0"
pandas = "^2.2.2"
numpy = "^2.1.0"
openpyxl = "^3.1.5"
requests = "^2.32.3"
pydantic = "^2.8.2"
pydub = "^0.25.1"
ffmpeg-python = "^0.2.0"
fitz = "^0.0.1.dev2"
psycopg2 = "^2.9.9"
frontend = "^0.0.3"
pillow = "^10.4.0"
pymupdf = "^1.24.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
