[tool.poetry]
name = "video-analysis-assistant"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ffmpeg = "^1.4"
opencv-python = "^4.10.0.84"
openai = "^1.42.0"
pandas = "^2.2.2"
numpy = "^2.1.0"
openpyxl = "^3.1.5"
requests = "^2.32.3"
pydantic = "^2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
